name: secrets-scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          base: main
          head: HEAD
          # remove --no-update to avoid duplicate flag (action may set it internally)
          extra_args: --only-verified --exclude-paths .trufflehogignore

      - name: Secrets scan success
        run: echo "🔐 No secrets detected - scan passed!"
