name: secrets-scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog (pull_request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified --exclude-paths .trufflehogignore

      - name: TruffleHog (push)
        if: ${{ github.event_name == 'push' }}
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --only-verified --exclude-paths .trufflehogignore

      - name: Secrets scan success
        run: echo "🔐 No secrets detected - scan passed!"
